### ISSUE TITLE
启动失败，也没有更多的失败信息

### ISSUE THREAD

**Issue by dreambe** [t880216t/yutu-tools#1]
![image](https://user-images.githubusercontent.com/3831001/196116413-aa5baf18-3fdb-4c4a-b4b6-e8598a96406f.png)

**Comment by t880216t** [comment]
> ![image](https://user-images.githubusercontent.com/3831001/196116413-aa5baf18-3fdb-4c4a-b4b6-e8598a96406f.png)

报错显示没有连上 127.0.0.1:8888的hub

**Comment by WXBlank** [comment]
请问解决了吗

**Comment by t880216t** [comment]
不是本项目的问题，需要确保自己的selenium-hub的访问正常。

**Comment by WXBlank** [comment]
您好，您的邮件已收到~
